spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      # 逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 主键类型
      id-type: auto
      # 字段策略 非空判断
      field-strategy: not_empty
      # 驼峰下划线转换
      table-underline: true

