server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test
#      username: root
#      password: 123456
  elasticsearch:
    cluster-name: elasticsearch
    cluster-nodes: 127.0.0.1:9300
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual  #手动应答
      direct:
        acknowledge-mode: manual
    publisher-confirms: true # 开启消息确认机制
    publisher-returns: true  # 消息发送失败返回队列
  flyway:
    locations: classpath:db/migration
    enabled: true
    clean-disabled: true
    check-location: false
    baseline-on-migrate: true
    baseline-version: 0
    encoding: utf-8
    out-of-order: true
  security:
    user:
      name: smith
      password: 123456

#management:
#  server:
#    port: 8090
#    servlet:
#      context-path: /sys
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#      base-path: /actuator
#logging:
#  level:
#    com.demo: info

